FIXME: file descriptor leaks
- Originally, this was an attempt to diagnose concurrent DB access failures
  in https://github.com/ueno/podman-sequoia/actions/runs/16569419233/job/46857408844?pr=7 :
> thread 'signature::tests::verify' panicked at src/signature.rs:738:90:
> called `Result::unwrap()` on an `Err` value: database is locked

but spawning 100 threads trying to open/close the mechanism failed
... because just trying to repeatedly open/close the mechanism failed:
https://gitlab.com/sequoia-pgp/sequoia-keystore/-/issues/33 .

Signed-off-by: Miloslav Trmač <mitr@redhat.com>